--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kxle0801/KXLootbox
build-by-default: true
branches:
- main
projects:
  KXLootbox:
    path: ""
    icon: kxlootbox_icon.png
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
        branch: PM5
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: "pm5"
...
