name: KXLootbox
main: kxle\Main
api: 5.15.0
version: 0.1.2
author: KxlePH
description: "This plugin allows you to make your own Lootbox in-game. Fully Configurable and much more!"

permissions:
  permission.command:
    default: op
  permission.command.create:
    default: op
  permission.command.delete:
    default: op
  permission.command.give:
    default: op
  permission.command.list:
    default: op