name: KXLootbox
main: kxleph\kxlootbox\Main
api: 5.24.0
version: 0.2.3
author: KxlePH
description: "This plugin allows you to make your own Lootbox in-game. Fully Configurable and much more!"

permissions:
  kxlootbox.command:
    default: op
  kxlootbox.create:
    default: op
  kxlootbox.delete:
    default: op
  kxlootbox.give:
    default: op
  kxlootbox.list:
    default: op
